kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: node:alpine
    commands:
      - npm install
      - npx gatsby build
  - name: publish
    image: plugins/docker
    settings:
      auto_tag: true
      dockerfile: Dockerfile
      repo: registry.quaysi.de/benmatheja/start
      registry: registry.quaysi.de
    when:
      branch:
      - master