kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: plugins/docker
    settings:
      auto_tag: true
      dockerfile: Dockerfile
      repo: benmatheja/start
      registry: registry.quaysi.de
