kind: pipeline
type: docker
name: build

steps:
  # Install
  - name: npm install
    image: node:alpine
    group: install
    commands:
      - npm install
  # Lint Gatsby
  - name: eslint
      group: install
      image: marcbachmann/eslint:5.10.0
  # Build Gatsby
  - name: Gatsby Build
    image: node:alpine
    commands:
      - npx gatsby build
  # Publish Docker-Container to Registry
  - name: Publish
    image: plugins/docker
    settings:
      auto_tag: true
      dockerfile: Dockerfile
      repo: registry.quaysi.de/benmatheja/start
      registry: registry.quaysi.de
    when:
      branch:
      - master
  # Deploy to Host
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 192.168.1.9
      port: 22
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      script_stop: true
      script:
        - cd /opt/stack 
        - docker-compose pull start 
        - docker-compose up -d start  
    when:
      branch:
      - master
trigger:
  event:
    exclude:
    - pull_request